apiVersion: v1
kind: Service
metadata:
    name:  {{ .Release.Name }}-nodeport
    labels:
        env: {{.Values.env}}
spec:
    type: NodePort
    selector:
        app: deployment-{{ .Release.Name }}
    ports:
        - name: {{.Values.server.containerPort}}tcp01
          port: {{.Values.server.containerPort}}
          targetPort: {{.Values.server.containerPort}}


