apiVersion: v1
type: Opaque
kind: Secret
metadata:
    name:  {{ .Release.Name }}-secrets
    labels:
        env: {{.Values.env}}
data:
    DD_API_KEY: {{ .Values.secrets.DD_API_KEY | b64enc | quote }}
    database-helo-ddl-password: {{ .Values.secrets.database_helo_ddl_password | b64enc | quote }}
    database-helo-runtime-password: {{ .Values.secrets.database_helo_runtime_password | b64enc | quote }}


