apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-server
    labels:
        app: deployment-{{ .Release.Name }}
        env: {{.Values.env}}
spec:
    replicas: {{.Values.server.replicaCount}}
    selector:
        matchLabels:
            app: deployment-{{ .Release.Name }}
    template:
        metadata:
            labels:
                app: deployment-{{ .Release.Name }}
        spec:
            containers:
                - name: {{ .Release.Name }}-server
                  image: entsia/cod:server_{{.Values.server.imageTag | replace ":" ""}}
                  ports:
                      - containerPort: {{.Values.server.containerPort}}
                  volumeMounts:
                      - mountPath: /opt/jboss/wildfly/standalone/deployments/helo.war/WEB-INF/classes/secrets.properties
                        name: vol1
                      - mountPath: /opt/jboss/dd-java-agent.jar
                        name: vol2
                  envFrom:
                      - configMapRef:
                            name: {{ .Release.Name }}-configmap
                            optional: false
                      - secretRef:
                            name: {{ .Release.Name }}-secrets
                            optional: false
                  imagePullPolicy: Always
                  livenessProbe:
                      failureThreshold: 3
                      httpGet:
                          path: /status
                          port: {{.Values.server.containerPort}}
                          scheme: HTTP
                      initialDelaySeconds: 60
                      periodSeconds: 10
                      successThreshold: 1
                      timeoutSeconds: 10
                  readinessProbe:
                      failureThreshold: 3
                      httpGet:
                          path: /status
                          port: {{.Values.server.containerPort}}
                          scheme: HTTP
                      initialDelaySeconds: 60
                      periodSeconds: 10
                      successThreshold: 2
                      timeoutSeconds: 10
                  resources: {}
                  securityContext:
                      allowPrivilegeEscalation: false
                      capabilities: {}
                      privileged: false
                      procMount: Default
                      readOnlyRootFilesystem: false
                      runAsNonRoot: false
                  stdin: true
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  tty: true
            dnsPolicy: ClusterFirst
            imagePullSecrets:
                - name: {{.Values.server.imagePullSecrets}}
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
                - name: vol1
                  hostPath:
                      path: /mnt/efs/properties/{{.Values.env}}/secrets.properties
                - name: vol2
                  hostPath:
                      path: /mnt/efs/dataDog/dd-java-agent.jar

