# Default values for chubb-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: st

configmap:
  dd_agent_host: datadog
  dd_apm_enabled: true
  dd_service_name: CHUBB_ON_DEMAND_ST
  dd_trace_agent_port: 32441
  database_helo_ddl_username: st_cod_helo
  database_helo_runtime_username: st_cod_helo_runtime
  java_opts: "-Xms64m -Xmx2048m -XX:MetaspaceSize=96M -Djava.net.preferIPv4Stack=true -javaagent:/opt/jboss/dd-java-agent.jar"
  db_hostname: chubb-avmh-nonprodrds-01.cteodrvok6fw.ap-southeast-2.rds.amazonaws.com

secrets:
  DD_API_KEY: 4491452dc4ed27d50dae68db230d6142
  database_helo_ddl_password: Pa55w0rd
  database_helo_runtime_password: Pa55w0rd

server:
  name: server-test
  containerPort: 6060
  vol1Path: /mnt/efs/dataDog/dd-java-agent.jar
  vol2Path: /mnt/efs/properties/st/secrets.properties
  imageTag: 201904080956
  replicaCount: 1