apiVersion: v1
kind: ConfigMap
metadata:
    name: rc-config-map
    labels:
        env: rc
data:
    DD_AGENT_HOST: {{.Values.datadog.DD_AGENT_HOST}}
    DD_APM_ENABLED: "{{.Values.datadog.DD_APM_ENABLED}}"
    DD_SERVICE_NAME: {{.Values.datadog.DD_SERVICE_NAME}}
    DD_TRACE_AGENT_PORT: "{{.Values.DD_TRACE_AGENT_PORT}}"
    JAVA_OPTS: {{.Values.server.JAVA_OPTS}}
    database-helo-ddl-username: {{.Values.database.database_helo_ddl_username}}
    database-helo-runtime-username: {{.Values.database.database_helo_runtime_username}}
    db-hostname: {{.Values.database.db_hostname}}
