apiVersion: v1
kind: ConfigMap
metadata:
  name: rc-config-map
  labels:
    env: rc
data:
  DD_AGENT_HOST: datadog
  DD_APM_ENABLED: "true"
  DD_SERVICE_NAME: CHUBB_ON_DEMAND_RC
  DD_TRACE_AGENT_PORT: "32441"
  JAVA_OPTS: -Xms64m -Xmx2048m -XX:MetaspaceSize=96M -Djava.net.preferIPv4Stack=true -javaagent:/opt/jboss/dd-java-agent.jar
  database-helo-ddl-username: rc_cod_helo
  database-helo-runtime-username: rc_cod_helo_runtime
  postgres-hostname: entsia-avmh-rds-01.coaeljwic7t7.ap-southeast-2.rds.amazonaws.com
