apiVersion: v1
kind: ConfigMap
metadata:
    name: st-config-map
    labels:
        env: st
data:
    DD_AGENT_HOST: {{.Values.datadog.dd_agent_host}}
    DD_APM_ENABLED: {{.Values.datadog.dd_apm_enabled}}
    DD_SERVICE_NAME: {{.Values.datadog.dd_service_name}}
    DD_TRACE_AGENT_PORT: {{.Values.datadog.dd_trace_agent_port}}
    JAVA_OPTS: {{.Values.java_opts}}
    database-helo-ddl-username: {{.Values.platform.database_helo_ddl_username}}
    database-helo-runtime-username: {{.Values.platform.database_helo_runtime_username}}
    db-hostname: {{.Values.platform.db_hostname}}
