apiVersion: v1
kind: ConfigMap
metadata:
    name: st-config-map
    labels:
        env: st
data:
    DD_AGENT_HOST: datadog
    DD_APM_ENABLED: true
    DD_SERVICE_NAME: CHUBB_ON_DEMAND_ST
    DD_TRACE_AGENT_PORT: {{.Values.dd_trace_agent_port}}
    JAVA_OPTS: "-Xms64m -Xmx2048m -XX:MetaspaceSize=96M -Djava.net.preferIPv4Stack=true -javaagent:/opt/jboss/dd-java-agent.jar"
    database-helo-ddl-username: st_cod_helo
    database-helo-runtime-username: st_cod_helo_runtime
    postgres-hostname: "entsia-avmh-rds-01.coaeljwic7t7.ap-southeast-2.rds.amazonaws.com"
