apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-server-test
  name: server-test
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-server-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-server-test
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: st-secrets
            optional: false
        - configMapRef:
            name: st-configmap
            optional: false
        image: entsia/cod:server_201904080956
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 6060
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: server-test
        ports:
        - containerPort: 6060
          name: 6060tcp01
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 6060
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 2
          timeoutSeconds: 10
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /opt/jboss/wildfly/standalone/deployments/helo.war/WEB-INF/classes/secrets.properties
          name: vol1
        - mountPath: /opt/jboss/dd-java-agent.jar
          name: vol2
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhubentsia
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /mnt/efs/properties/st/secrets.properties
          type: ""
        name: vol1
      - hostPath:
          path: /mnt/efs/dataDog/dd-java-agent.jar
          type: ""
        name: vol2
status: {}
