apiVersion: v1
kind: ConfigMap
metadata:
    name: uat-config-map
    labels:
        env: uat
data:
    DD_AGENT_HOST: {{.Values.DD_AGENT_HOST}}
    DD_APM_ENABLED: "{{.Values.DD_APM_ENABLED}}"
    DD_SERVICE_NAME: {{.Values.DD_SERVICE_NAME}}
    DD_TRACE_AGENT_PORT: "{{.Values.DD_TRACE_AGENT_PORT}}"
    JAVA_OPTS: {{.Values.JAVA_OPTS}}
    database-helo-ddl-username: {{.Values.database_helo_ddl_username}}
    database-helo-runtime-username: {{.Values.database_helo_runtime_username}}
    db-hostname: {{.Values.db_hostname}}
    base3: {{.Values.base3}}
